### ISSUE TITLE
timeline.jsのエラーハンドリングがおかしそう

### ISSUE THREAD

**Issue by ara-ta3** [ngineerxiv/dark-bot#225]
Slackの調子が悪くて死んでしまったっぽさ？
だけど、timeline.jsも微妙にエラーハンドリングうまくできてなさそう

```
[Tue Aug 16 2016 23:29:42 GMT+0900 (JST)] ERROR { [Error: ETIMEDOUT] code: 'ETIMEDOUT', connect: false }
[Tue Aug 16 2016 23:29:42 GMT+0900 (JST)] ERROR SyntaxError: Unexpected token u
  at Object.parse (native)
  at Request._callback (/web/httpd_arata/dark-bot/src/scripts/timeline.js:79:29)
  at self.callback (/web/httpd_arata/dark-bot/node_modules/request/request.js:187:22)
  at emitOne (events.js:90:13)
  at Request.emit (events.js:182:7)
  at Timeout._onTimeout (/web/httpd_arata/dark-bot/node_modules/request/request.js:762:12)
  at tryOnTimeout (timers.js:224:11)
  at Timer.listOnTimeout (timers.js:198:5)

[Tue Aug 16 2016 23:29:42 GMT+0900 (JST)] ERROR [SyntaxError: Unexpected token u]
[Wed Aug 17 2016 03:06:43 GMT+0900 (JST)] INFO Slack client connection was closed, exiting hubot process
make: Leaving directory `/web/httpd_arata/dark-bot'
make: Entering directory `/web/httpd_arata/dark-bot'
env NODE_ENV=production ./bin/hubot-slack /credentials/dark-bot-for-ngineerxiv --monitoring-code=dark-bot-ngineerxiv
[Wed Aug 17 2016 03:07:07 GMT+0900 (JST)] INFO Connecting...
[Wed Aug 17 2016 03:07:08 GMT+0900 (JST)] ERROR undefined
```

**Comment by ara-ta3** [comment]
対策は打ったのでいったん様子見
